server:
  port: 8081
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/princenim/spring-cloud-config
          default-label: master

# actuator 설정
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      enabled: true


      

